import type { Catalogue } from "./catalogue.types.js";

export const CATALOGUE_V1: Catalogue = Object.freeze({
  version: "1",
  budget: 100,
  chassis: Object.freeze([
    Object.freeze({
      id: "light",
      name: "Light",
      cost: 15,
      integrity: 60,
      baseMass: 10,
      agility: 9,
      stability: 4,
    }),
    Object.freeze({
      id: "medium",
      name: "Medium",
      cost: 25,
      integrity: 100,
      baseMass: 20,
      agility: 6,
      stability: 6,
    }),
    Object.freeze({
      id: "heavy",
      name: "Heavy",
      cost: 40,
      integrity: 150,
      baseMass: 35,
      agility: 3,
      stability: 9,
    }),
  ]),
  mobility: Object.freeze([
    Object.freeze({
      id: "wheels",
      name: "Wheels",
      cost: 12,
      speed: 9,
      traction: 6,
      turning: 9,
      stabilityModifier: 0,
    }),
    Object.freeze({
      id: "tracks",
      name: "Tracks",
      cost: 20,
      speed: 5,
      traction: 9,
      turning: 5,
      stabilityModifier: 2,
    }),
    Object.freeze({
      id: "legs",
      name: "Legs",
      cost: 25,
      speed: 6,
      traction: 7,
      turning: 7,
      stabilityModifier: 1,
    }),
  ]),
  weapons: Object.freeze([
    Object.freeze({
      id: "ram",
      name: "Ram",
      cost: 10,
      baseDamage: 20,
      accuracy: 80,
      cooldown: 1,
      trait: "scales with speed",
    }),
    Object.freeze({
      id: "hammer",
      name: "Hammer",
      cost: 20,
      baseDamage: 35,
      accuracy: 65,
      cooldown: 2,
      trait: "strong top attacks",
    }),
    Object.freeze({
      id: "horizontal_spinner",
      name: "Horizontal Spinner",
      cost: 30,
      baseDamage: 50,
      accuracy: 55,
      cooldown: 3,
      trait: "high knockback",
    }),
    Object.freeze({
      id: "grappler",
      name: "Grappler",
      cost: 20,
      baseDamage: 10,
      accuracy: 80,
      cooldown: 2,
      trait: "control and reposition",
    }),
    Object.freeze({
      id: "flipper",
      name: "Flipper",
      cost: 25,
      baseDamage: 25,
      accuracy: 65,
      cooldown: 3,
      trait: "overturn chance",
    }),
  ]),
  utilities: Object.freeze([
    Object.freeze({
      id: "none",
      name: "None",
      cost: 0,
      effect: "no utility",
    }),
    Object.freeze({
      id: "cooling",
      name: "Cooling",
      cost: 10,
      effect: "improved heat recovery",
    }),
    Object.freeze({
      id: "traction_boost",
      name: "Traction Boost",
      cost: 10,
      effect: "improved movement and ram resistance",
    }),
    Object.freeze({
      id: "reinforced_drive",
      name: "Reinforced Drive",
      cost: 15,
      effect: "reduced mobility-component damage",
    }),
  ]),
  armour: Object.freeze({
    costPerTenPoints: 1,
    maxPerZone: 60,
    maxTotal: 120,
  }),
});
